wspring.application.name=entrega
gg.jte.development-mode=true

# Configuracion H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Configuracion de base de datos postgresql
spring.datasource.url=jdbc:postgresql://192.168.0.19:5432/entrega_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sergio
spring.datasource.password=123

# Configuracion JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Inicializacion SQL
spring.sql.init.mode=always

#Logging
#permite imprimir la query
logging.level.org.hibernate.SQL=DEBUG
#imprime los parametros de las querys
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Configuracion de base de datos postgresql
#spring.datasource.url=jdbc:postgresql://localhost:5432/entrega_db
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.username=sergio
#spring.datasource.password=123
